### ISSUE TITLE
Multiple display bugs in v15/v16 icons

### ISSUE THREAD

**Issue by rugk** [rugk/streetcomplete-quest-svgs#13]
Similar to the old case at https://github.com/rugk/streetcomplete-quest-svgs/issues/3 we do have display bugs again. 😢 

Only at Wikimedia, seems their converter to PNG fails again. If you look at the original with Firefox, it still seems to work.

![grafik](https://user-images.githubusercontent.com/11966684/73287613-ca01d000-41f9-11ea-9a20-245ed61cd963.png)
https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_recycling_glass.svg

![grafik](https://user-images.githubusercontent.com/11966684/73287621-cec68400-41f9-11ea-8518-f00288dc621b.png)
https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_fee.svg

![grafik](https://user-images.githubusercontent.com/11966684/73287628-d38b3800-41f9-11ea-88eb-e92a48fbae31.png)
https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_mail_ref.svg

---

This is annoying and needs a workaround. (may even be the same problem as in the old bug #3)

version: https://github.com/rugk/streetcomplete-quest-svgs/commit/186803d28524249b395ac7e1bae88af3ab22de95

/cc @westnordost

**Comment by rugk** [comment]
Another one...

![grafik](https://user-images.githubusercontent.com/11966684/73288764-dedf6300-41fb-11ea-9afb-c03192155f47.png)
https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_no_pedestrians.svg

**Comment by Binnette** [comment]
Hi @rugk, i will do a PR to fix those SVG this evening :wink:

**Comment by rugk** [comment]
Okay… (says /me one day later :stuck_out_tongue_winking_eye:)

**Comment by Binnette** [comment]
Hi @rugk, i fixed the SVG in #14

I do the strict minimum on the SVG in Inskacpe folder to make them compatible with mediawiki.

And of course, I fixed and saved as optimized the ones in folder 'optimized'.

Have a nice day :)
