### ISSUE TITLE
icon with zebra crossing look strange

### ISSUE THREAD

**Issue by rugk** [rugk/streetcomplete-quest-svgs#3]
This is how it looks in Inkscape:
![grafik](https://user-images.githubusercontent.com/11966684/29752482-21d33994-8b5f-11e7-996c-07718c24db88.png)

In the repo and on https://wiki.openstreetmap.org/wiki/File:StreetComplete_quest_tactile_paving_crossing.svg in Firefox 55.0.2 on Linux it looks strange here:
![grafik](https://user-images.githubusercontent.com/11966684/29752487-38f395ce-8b5f-11e7-93a7-c237c0026f4c.png)

Note that `StreetComplete_quest_tactilepaving.svg` looks fine.

**Comment by rugk** [comment]
Also affects `StreetComplete_quest_crossing.svg`.

**Comment by rugk** [comment]
Upstream: https://github.com/scour-project/scour/issues/153

**Comment by rugk** [comment]
Asked on https://graphicdesign.stackexchange.com/questions/97376/only-inkscape-shows-icon-correctly-on-linux.

**Comment by westnordost** [comment]
You can workaround this by selecting the figure and selecting "Stroke to path", cut the newly created path, undo, paste it at the same position. Then, remove the stroke paint from the original figure.
(So you have one shape for the stroke and one shape for the fill)

**Comment by rugk** [comment]
Uh, interesting you know a workaround. (And thanks for your info.) Still, I'd (first) rather first try to figure out the root cause and at least create some issues at Inkscape or so, as this is just a bug somehow/somewhere…

**Comment by rugk** [comment]
So actually just clicking on "Stroke to path" did the trick. Thanks for that. (As far as I see/kinow the object is just converted to a path then, so there is no duplicate object I may remove.)

BTW if you are on Stackexchange (and want to gain some upvotes or so), feel free to comment [on my question](https://graphicdesign.stackexchange.com/questions/97376/only-inkscape-and-github-render-svg-correctly/97377) with more details or so…

**Comment by rugk** [comment]
So in the end it is an incompatibility with "paint-order", as it turns out.
Don't know what to do here. For now, I'll just keep the workaround.

Thus closing this. 😃
