### ISSUE TITLE
Minimize images

### ISSUE THREAD

**Issue by rugk** [rugk/streetcomplete-quest-svgs#6]
Originally I saved all images in the `optimized/` dir only by choosing "Optimised SVG" in Inkscape. As [I've described](https://github.com/rugk/streetcomplete-quest-svgs/blob/master/CONTRIBUTING.md#minimize-svg-image) you could however still minimize them even more with that tool.

**Comment by goldfndr** [comment]
Indeed. While the "old" optimized ic_quest_notes.svg was using 4 decimal places, the "new" optimized one is using 8, even more than the unoptimized's 6-7. That seems like an easy bug report for whatever tool you used.

**Comment by rugk** [comment]
The thing is now I optimize the images using SVGOMG. (see contributing) Previously I only minimized them using Inkscape.

This is an easy PR for anyone who just wants to optimize all images in the "optimized" dir. If anyone wants to do some batch (or manual) processing there.

**Comment by goldfndr** [comment]
>The thing is now I optimize the images using SVGOMG

You did? I tried it just now (via pasting the source code of the optimized image in the web interface) and it reduced the precision of the decimals to 3 places. Hmm...

**Comment by rugk** [comment]
Well… yeah, because I am stupid. That is meant with precision there…

As I write in the Contributing:
> Select the highest possible precision.

I'll change that.

If you want to re-optimize them with 3 decimal places (I think that is enough), just do so.
In any case the issue here, is about optimizing all images, anyway.

**Comment by Binnette** [comment]
Is it that important to shrink files from 5.5 Ko to 5.3 Ko?

**Comment by rugk** [comment]
No.
